# Numpy

In [1]:
import numpy as np 

In [2]:
np.__version__

'2.1.3'

In [3]:
import sys 
sys.version

'3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, 16:37:03) [MSC v.1929 64 bit (AMD64)]'

## Creating LIST

In [4]:
my_list = [0,1,2,3,4,5]
my_list 

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

# below code we are converting list to array

In [6]:
#!pip install numpy

In [7]:
arr = np.array(my_list) 

In [8]:
arr

array([0, 1, 2, 3, 4, 5])

In [9]:
type(arr)

numpy.ndarray

In [10]:
type(my_list)

list

In [11]:
np. # we learn important function 

SyntaxError: invalid syntax (1655120754.py, line 1)

In [12]:
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(5.0)   

array([0., 1., 2., 3., 4.])

In [14]:
np.arange(9) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
np.arange(0, 5) 

array([0, 1, 2, 3, 4])

In [16]:
np.arange(10,20) 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
np.arange(20,10) # 1st arg < 2nd arg

array([], dtype=int64)

In [18]:
np.arange(-20,10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [19]:
np.arange(-16,10) 

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [20]:
np.arange(-20,-10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [21]:
np.arange(30,20)  # 1st arg always be < then 2nd arg

array([], dtype=int64)

In [22]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [23]:
np.arange(10,10) 

array([], dtype=int64)

In [24]:
np.arange()

TypeError: arange() requires stop to be specified.

In [ ]:
np.arange(10,30,5)  # 10- starting from 30- end point 5 - step count

In [ ]:
np.arange(0,10,3)

In [ ]:
np.arange(10,30,5,8)

In [ ]:
np.zeros(10) # parameter  tunning 

In [ ]:
np.zeros(5, dtype=int) # hyperparameter tunning 

In [ ]:
np.zeros((2,2), dtype=int)

In [ ]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

In [ ]:
zero = np.zeros([2,2])
print(zero)

print('####')

print(type(zero))

In [25]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [26]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [27]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [29]:
np.zeros((10,10),dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [30]:
np.zeros((5,10)) # bydefaul 1arge -- will give row & 2nd arg - columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1)) # parameter tunnin g

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [32]:
print(np.zeros(n,dtype=int)) ## hypyerparameter tunning 

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [33]:
n

(6, 7)

In [34]:
n1

(6, 8)

In [35]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [36]:
np.ones(3)

array([1., 1., 1.])

In [37]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [38]:
np.ones(4, dtype=int) 

array([1, 1, 1, 1])

In [39]:
np.ones(4)

array([1., 1., 1., 1.])

In [40]:
n

(6, 7)

In [41]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [42]:
np.ones((5,4),dtype=int) # by default 5- rows & 4 - columns

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [43]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [ ]:
np.two((2,3)) 

In [44]:
np.three(2,3) 

AttributeError: module 'numpy' has no attribute 'three'

In [ ]:
np.ones(2)

In [ ]:
np.ones((2,4)) 

In [ ]:
np.ones((6,10),dtype = int) 

In [ ]:
np.twos((2,4))

In [ ]:
np.

In [ ]:
np.three((2,4))

In [45]:
range(5)

range(0, 5)

In [46]:
r = range(5)
r

range(0, 5)

In [47]:
for i in r:
    print(i)

0
1
2
3
4


In [48]:
list(range(5))

[0, 1, 2, 3, 4]

In [49]:
range(1,10)

range(1, 10)

In [50]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [51]:
list(range(1,10,3))

[1, 4, 7]

In [52]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [53]:
rand(3,2)

NameError: name 'rand' is not defined

In [ ]:
random.rand(3,2)

In [54]:
np.random.rand(5)

array([0.91163668, 0.0530568 , 0.27650243, 0.50824783, 0.56762927])

In [55]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [ ]:
np.random.rand(3,5)

In [ ]:
np.random.randint(4,6)

In [ ]:
np.random.randint(2,20,4) # 2nd argument is exlusive 

In [ ]:
np.random.randint(0,1) 

In [56]:
np.random.randint(10,20,5)

array([15, 12, 19, 17, 19], dtype=int32)

In [57]:
np.random.randint(1,6,4)

array([3, 4, 2, 4], dtype=int32)

In [58]:
np.random.rand(3)

array([0.11117045, 0.78696663, 0.98159267])

In [59]:
np.random.randint(1)  

0

In [60]:
np.random.randint(30,20,10) 

ValueError: low >= high

In [ ]:
np.random.randint(-30,20,10) 

In [61]:
np.random.randint(20,30,10) 

array([29, 22, 22, 20, 21, 29, 29, 22, 24, 28], dtype=int32)

In [62]:
np.random.randint(5,9)  #GET THE VALUE <=1 & >=5

7

In [63]:
np.random.randint(10,21,3)

array([18, 17, 15], dtype=int32)

In [64]:
np.random.randint(1,12,10)

array([ 8, 11,  8,  5,  3, 11,  1, 10,  2,  6], dtype=int32)

In [65]:
np.random.randint(10,40,(10,10)) #generre the element 10 -30 with 4*4 mtri

array([[14, 36, 14, 33, 32, 15, 14, 14, 17, 21],
       [39, 19, 19, 17, 35, 20, 14, 34, 15, 28],
       [20, 23, 32, 37, 33, 27, 26, 27, 16, 17],
       [15, 32, 24, 39, 19, 39, 17, 25, 18, 11],
       [33, 10, 10, 39, 32, 14, 33, 12, 25, 18],
       [39, 31, 33, 20, 28, 10, 32, 27, 19, 39],
       [20, 37, 19, 38, 23, 22, 33, 13, 35, 15],
       [16, 27, 32, 28, 23, 31, 19, 18, 36, 35],
       [32, 17, 34, 36, 29, 35, 28, 20, 36, 34],
       [21, 27, 22, 27, 24, 20, 17, 37, 26, 29]], dtype=int32)

In [66]:
np.random.randint(1,100,(12,12)) #generre the element 10 -30 with 4*4 mtri

array([[49,  2, 70, 84,  4, 56, 77, 92, 28, 35,  6, 65],
       [30, 28, 43, 24, 67, 80, 17,  7, 13,  2, 52, 29],
       [85, 48, 37, 43, 93, 25, 40, 84, 84,  7, 53, 30],
       [22, 82, 16, 77, 77, 66, 13, 20, 31, 30,  3, 74],
       [76, 23, 18, 36, 50,  5, 36, 30, 19, 18, 46, 42],
       [63,  1,  8, 65, 50,  7, 31, 87, 66, 35, 68,  4],
       [77, 54, 43, 17, 91, 25, 65,  7, 90, 29, 20, 81],
       [53, 11, 91, 98, 26, 73, 56, 78, 97, 57, 10, 96],
       [ 5, 88, 23,  5, 10,  3, 99, 93, 63, 83,  7, 17],
       [67, 25, 65, 41, 34, 13, 40, 10, 37, 14, 58,  5],
       [39, 26, 44, 70, 14, 42, 58, 67, 94, 48, 58, 67],
       [63, 75, 83, 81, 99, 18, 77, 35,  2, 92, 27,  3]], dtype=int32)

In [67]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [68]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [69]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [70]:
np.arange(1,13).reshape(5,4)

ValueError: cannot reshape array of size 12 into shape (5,4)

In [ ]:
np.arange(1,13).reshape(6,2)

In [71]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

# slicing in matrix

In [72]:
b = np.random.randint(10,20,(5,4))
b

array([[12, 19, 16, 19],
       [12, 17, 15, 11],
       [18, 15, 16, 16],
       [10, 19, 14, 16],
       [16, 16, 10, 10]], dtype=int32)

In [73]:
type(b)

numpy.ndarray

In [74]:
b

array([[12, 19, 16, 19],
       [12, 17, 15, 11],
       [18, 15, 16, 16],
       [10, 19, 14, 16],
       [16, 16, 10, 10]], dtype=int32)

In [75]:
b[:] 

array([[12, 19, 16, 19],
       [12, 17, 15, 11],
       [18, 15, 16, 16],
       [10, 19, 14, 16],
       [16, 16, 10, 10]], dtype=int32)

In [76]:
b[1:3]

array([[12, 17, 15, 11],
       [18, 15, 16, 16]], dtype=int32)

In [77]:
b

array([[12, 19, 16, 19],
       [12, 17, 15, 11],
       [18, 15, 16, 16],
       [10, 19, 14, 16],
       [16, 16, 10, 10]], dtype=int32)

In [78]:
b[1,2]

np.int32(15)

In [79]:
b

array([[12, 19, 16, 19],
       [12, 17, 15, 11],
       [18, 15, 16, 16],
       [10, 19, 14, 16],
       [16, 16, 10, 10]], dtype=int32)

In [80]:
b[1,3]

np.int32(11)

In [81]:
b

array([[12, 19, 16, 19],
       [12, 17, 15, 11],
       [18, 15, 16, 16],
       [10, 19, 14, 16],
       [16, 16, 10, 10]], dtype=int32)

In [82]:
b[1,-1]

np.int32(11)

In [83]:
b

array([[12, 19, 16, 19],
       [12, 17, 15, 11],
       [18, 15, 16, 16],
       [10, 19, 14, 16],
       [16, 16, 10, 10]], dtype=int32)

In [84]:
b[2:3]

array([[18, 15, 16, 16]], dtype=int32)

In [85]:
b

array([[12, 19, 16, 19],
       [12, 17, 15, 11],
       [18, 15, 16, 16],
       [10, 19, 14, 16],
       [16, 16, 10, 10]], dtype=int32)

In [86]:
b[0:-2] 

array([[12, 19, 16, 19],
       [12, 17, 15, 11],
       [18, 15, 16, 16]], dtype=int32)

In [87]:
b

array([[12, 19, 16, 19],
       [12, 17, 15, 11],
       [18, 15, 16, 16],
       [10, 19, 14, 16],
       [16, 16, 10, 10]], dtype=int32)

In [88]:
b[0,2] 

np.int32(16)

In [89]:
b

array([[12, 19, 16, 19],
       [12, 17, 15, 11],
       [18, 15, 16, 16],
       [10, 19, 14, 16],
       [16, 16, 10, 10]], dtype=int32)

In [90]:
b[-5,3] 

np.int32(19)

In [91]:
b[-5,-3]

np.int32(19)

In [92]:
b

array([[12, 19, 16, 19],
       [12, 17, 15, 11],
       [18, 15, 16, 16],
       [10, 19, 14, 16],
       [16, 16, 10, 10]], dtype=int32)

In [93]:
b[-4,2] 

np.int32(15)

In [94]:
np.random.randint(10,20,(4,4))

array([[10, 12, 18, 11],
       [12, 10, 11, 13],
       [10, 16, 17, 16],
       [19, 19, 18, 13]], dtype=int32)

In [95]:
b 

array([[12, 19, 16, 19],
       [12, 17, 15, 11],
       [18, 15, 16, 16],
       [10, 19, 14, 16],
       [16, 16, 10, 10]], dtype=int32)

In [96]:
b[-4,-2]

np.int32(15)

In [97]:
b

array([[12, 19, 16, 19],
       [12, 17, 15, 11],
       [18, 15, 16, 16],
       [10, 19, 14, 16],
       [16, 16, 10, 10]], dtype=int32)

In [98]:
b[-4:2] 

array([[12, 17, 15, 11]], dtype=int32)

In [99]:
b[:]

array([[12, 19, 16, 19],
       [12, 17, 15, 11],
       [18, 15, 16, 16],
       [10, 19, 14, 16],
       [16, 16, 10, 10]], dtype=int32)

## Operations

In [100]:
a = np.random.randint(10,20,10)
a

array([14, 11, 11, 18, 10, 14, 11, 17, 13, 14], dtype=int32)

In [101]:
id(a)

2818446115632

In [102]:
arr

array([0, 1, 2, 3, 4, 5])

In [103]:
arr2 = np.random.randint(0,100,(10,10))

In [104]:
arr2

array([[36, 67, 86, 83, 99, 54, 25, 99, 34, 65],
       [99, 38, 96, 76, 69, 84, 37, 61,  7, 19],
       [64, 17, 33, 90, 75, 87, 83, 70, 41, 79],
       [ 4, 44,  6,  6, 59, 83, 40, 51, 42,  2],
       [96, 12, 78, 37,  6,  0, 90, 91, 52, 71],
       [34, 46, 34, 99, 68, 62, 58, 66, 95, 12],
       [14, 68, 97, 36, 15, 54, 67, 96, 52, 81],
       [68, 47, 82, 53, 83, 52, 20, 51, 38, 72],
       [60, 90, 47, 72, 42, 73,  2, 65, 43, 47],
       [37, 61, 42, 51, 32, 23, 30, 45, 64, 95]], dtype=int32)

In [105]:
arr

array([0, 1, 2, 3, 4, 5])

In [106]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [107]:
arr

array([0, 1, 2, 3, 4, 5])

In [108]:
arr[:4] 

array([0, 1, 2, 3])

In [109]:
arr2[:]

array([[36, 67, 86, 83, 99, 54, 25, 99, 34, 65],
       [99, 38, 96, 76, 69, 84, 37, 61,  7, 19],
       [64, 17, 33, 90, 75, 87, 83, 70, 41, 79],
       [ 4, 44,  6,  6, 59, 83, 40, 51, 42,  2],
       [96, 12, 78, 37,  6,  0, 90, 91, 52, 71],
       [34, 46, 34, 99, 68, 62, 58, 66, 95, 12],
       [14, 68, 97, 36, 15, 54, 67, 96, 52, 81],
       [68, 47, 82, 53, 83, 52, 20, 51, 38, 72],
       [60, 90, 47, 72, 42, 73,  2, 65, 43, 47],
       [37, 61, 42, 51, 32, 23, 30, 45, 64, 95]], dtype=int32)

In [110]:
arr2[0:5] 

array([[36, 67, 86, 83, 99, 54, 25, 99, 34, 65],
       [99, 38, 96, 76, 69, 84, 37, 61,  7, 19],
       [64, 17, 33, 90, 75, 87, 83, 70, 41, 79],
       [ 4, 44,  6,  6, 59, 83, 40, 51, 42,  2],
       [96, 12, 78, 37,  6,  0, 90, 91, 52, 71]], dtype=int32)

In [111]:
arr2

array([[36, 67, 86, 83, 99, 54, 25, 99, 34, 65],
       [99, 38, 96, 76, 69, 84, 37, 61,  7, 19],
       [64, 17, 33, 90, 75, 87, 83, 70, 41, 79],
       [ 4, 44,  6,  6, 59, 83, 40, 51, 42,  2],
       [96, 12, 78, 37,  6,  0, 90, 91, 52, 71],
       [34, 46, 34, 99, 68, 62, 58, 66, 95, 12],
       [14, 68, 97, 36, 15, 54, 67, 96, 52, 81],
       [68, 47, 82, 53, 83, 52, 20, 51, 38, 72],
       [60, 90, 47, 72, 42, 73,  2, 65, 43, 47],
       [37, 61, 42, 51, 32, 23, 30, 45, 64, 95]], dtype=int32)

In [112]:
arr2[1,4] 

np.int32(69)

In [113]:
arr2

array([[36, 67, 86, 83, 99, 54, 25, 99, 34, 65],
       [99, 38, 96, 76, 69, 84, 37, 61,  7, 19],
       [64, 17, 33, 90, 75, 87, 83, 70, 41, 79],
       [ 4, 44,  6,  6, 59, 83, 40, 51, 42,  2],
       [96, 12, 78, 37,  6,  0, 90, 91, 52, 71],
       [34, 46, 34, 99, 68, 62, 58, 66, 95, 12],
       [14, 68, 97, 36, 15, 54, 67, 96, 52, 81],
       [68, 47, 82, 53, 83, 52, 20, 51, 38, 72],
       [60, 90, 47, 72, 42, 73,  2, 65, 43, 47],
       [37, 61, 42, 51, 32, 23, 30, 45, 64, 95]], dtype=int32)

In [114]:
arr2[-5,5] 

np.int32(62)

In [115]:
arr2[-5,-5] 

np.int32(62)

In [116]:
arr2

array([[36, 67, 86, 83, 99, 54, 25, 99, 34, 65],
       [99, 38, 96, 76, 69, 84, 37, 61,  7, 19],
       [64, 17, 33, 90, 75, 87, 83, 70, 41, 79],
       [ 4, 44,  6,  6, 59, 83, 40, 51, 42,  2],
       [96, 12, 78, 37,  6,  0, 90, 91, 52, 71],
       [34, 46, 34, 99, 68, 62, 58, 66, 95, 12],
       [14, 68, 97, 36, 15, 54, 67, 96, 52, 81],
       [68, 47, 82, 53, 83, 52, 20, 51, 38, 72],
       [60, 90, 47, 72, 42, 73,  2, 65, 43, 47],
       [37, 61, 42, 51, 32, 23, 30, 45, 64, 95]], dtype=int32)

In [117]:
arr2[-5,-5]

np.int32(62)

In [118]:
arr2

array([[36, 67, 86, 83, 99, 54, 25, 99, 34, 65],
       [99, 38, 96, 76, 69, 84, 37, 61,  7, 19],
       [64, 17, 33, 90, 75, 87, 83, 70, 41, 79],
       [ 4, 44,  6,  6, 59, 83, 40, 51, 42,  2],
       [96, 12, 78, 37,  6,  0, 90, 91, 52, 71],
       [34, 46, 34, 99, 68, 62, 58, 66, 95, 12],
       [14, 68, 97, 36, 15, 54, 67, 96, 52, 81],
       [68, 47, 82, 53, 83, 52, 20, 51, 38, 72],
       [60, 90, 47, 72, 42, 73,  2, 65, 43, 47],
       [37, 61, 42, 51, 32, 23, 30, 45, 64, 95]], dtype=int32)

In [119]:
arr2[-1,-2]

np.int32(64)

In [120]:
arr2

array([[36, 67, 86, 83, 99, 54, 25, 99, 34, 65],
       [99, 38, 96, 76, 69, 84, 37, 61,  7, 19],
       [64, 17, 33, 90, 75, 87, 83, 70, 41, 79],
       [ 4, 44,  6,  6, 59, 83, 40, 51, 42,  2],
       [96, 12, 78, 37,  6,  0, 90, 91, 52, 71],
       [34, 46, 34, 99, 68, 62, 58, 66, 95, 12],
       [14, 68, 97, 36, 15, 54, 67, 96, 52, 81],
       [68, 47, 82, 53, 83, 52, 20, 51, 38, 72],
       [60, 90, 47, 72, 42, 73,  2, 65, 43, 47],
       [37, 61, 42, 51, 32, 23, 30, 45, 64, 95]], dtype=int32)

In [121]:
arr2[::-1]

array([[37, 61, 42, 51, 32, 23, 30, 45, 64, 95],
       [60, 90, 47, 72, 42, 73,  2, 65, 43, 47],
       [68, 47, 82, 53, 83, 52, 20, 51, 38, 72],
       [14, 68, 97, 36, 15, 54, 67, 96, 52, 81],
       [34, 46, 34, 99, 68, 62, 58, 66, 95, 12],
       [96, 12, 78, 37,  6,  0, 90, 91, 52, 71],
       [ 4, 44,  6,  6, 59, 83, 40, 51, 42,  2],
       [64, 17, 33, 90, 75, 87, 83, 70, 41, 79],
       [99, 38, 96, 76, 69, 84, 37, 61,  7, 19],
       [36, 67, 86, 83, 99, 54, 25, 99, 34, 65]], dtype=int32)

In [122]:
arr2

array([[36, 67, 86, 83, 99, 54, 25, 99, 34, 65],
       [99, 38, 96, 76, 69, 84, 37, 61,  7, 19],
       [64, 17, 33, 90, 75, 87, 83, 70, 41, 79],
       [ 4, 44,  6,  6, 59, 83, 40, 51, 42,  2],
       [96, 12, 78, 37,  6,  0, 90, 91, 52, 71],
       [34, 46, 34, 99, 68, 62, 58, 66, 95, 12],
       [14, 68, 97, 36, 15, 54, 67, 96, 52, 81],
       [68, 47, 82, 53, 83, 52, 20, 51, 38, 72],
       [60, 90, 47, 72, 42, 73,  2, 65, 43, 47],
       [37, 61, 42, 51, 32, 23, 30, 45, 64, 95]], dtype=int32)

In [123]:
arr2[::-2] 

array([[37, 61, 42, 51, 32, 23, 30, 45, 64, 95],
       [68, 47, 82, 53, 83, 52, 20, 51, 38, 72],
       [34, 46, 34, 99, 68, 62, 58, 66, 95, 12],
       [ 4, 44,  6,  6, 59, 83, 40, 51, 42,  2],
       [99, 38, 96, 76, 69, 84, 37, 61,  7, 19]], dtype=int32)

In [124]:
arr2

array([[36, 67, 86, 83, 99, 54, 25, 99, 34, 65],
       [99, 38, 96, 76, 69, 84, 37, 61,  7, 19],
       [64, 17, 33, 90, 75, 87, 83, 70, 41, 79],
       [ 4, 44,  6,  6, 59, 83, 40, 51, 42,  2],
       [96, 12, 78, 37,  6,  0, 90, 91, 52, 71],
       [34, 46, 34, 99, 68, 62, 58, 66, 95, 12],
       [14, 68, 97, 36, 15, 54, 67, 96, 52, 81],
       [68, 47, 82, 53, 83, 52, 20, 51, 38, 72],
       [60, 90, 47, 72, 42, 73,  2, 65, 43, 47],
       [37, 61, 42, 51, 32, 23, 30, 45, 64, 95]], dtype=int32)

In [125]:
arr2[::-3]

array([[37, 61, 42, 51, 32, 23, 30, 45, 64, 95],
       [14, 68, 97, 36, 15, 54, 67, 96, 52, 81],
       [ 4, 44,  6,  6, 59, 83, 40, 51, 42,  2],
       [36, 67, 86, 83, 99, 54, 25, 99, 34, 65]], dtype=int32)

In [126]:
arr2

array([[36, 67, 86, 83, 99, 54, 25, 99, 34, 65],
       [99, 38, 96, 76, 69, 84, 37, 61,  7, 19],
       [64, 17, 33, 90, 75, 87, 83, 70, 41, 79],
       [ 4, 44,  6,  6, 59, 83, 40, 51, 42,  2],
       [96, 12, 78, 37,  6,  0, 90, 91, 52, 71],
       [34, 46, 34, 99, 68, 62, 58, 66, 95, 12],
       [14, 68, 97, 36, 15, 54, 67, 96, 52, 81],
       [68, 47, 82, 53, 83, 52, 20, 51, 38, 72],
       [60, 90, 47, 72, 42, 73,  2, 65, 43, 47],
       [37, 61, 42, 51, 32, 23, 30, 45, 64, 95]], dtype=int32)

In [127]:
arr2[:-3] 

array([[36, 67, 86, 83, 99, 54, 25, 99, 34, 65],
       [99, 38, 96, 76, 69, 84, 37, 61,  7, 19],
       [64, 17, 33, 90, 75, 87, 83, 70, 41, 79],
       [ 4, 44,  6,  6, 59, 83, 40, 51, 42,  2],
       [96, 12, 78, 37,  6,  0, 90, 91, 52, 71],
       [34, 46, 34, 99, 68, 62, 58, 66, 95, 12],
       [14, 68, 97, 36, 15, 54, 67, 96, 52, 81]], dtype=int32)

In [128]:
arr2

array([[36, 67, 86, 83, 99, 54, 25, 99, 34, 65],
       [99, 38, 96, 76, 69, 84, 37, 61,  7, 19],
       [64, 17, 33, 90, 75, 87, 83, 70, 41, 79],
       [ 4, 44,  6,  6, 59, 83, 40, 51, 42,  2],
       [96, 12, 78, 37,  6,  0, 90, 91, 52, 71],
       [34, 46, 34, 99, 68, 62, 58, 66, 95, 12],
       [14, 68, 97, 36, 15, 54, 67, 96, 52, 81],
       [68, 47, 82, 53, 83, 52, 20, 51, 38, 72],
       [60, 90, 47, 72, 42, 73,  2, 65, 43, 47],
       [37, 61, 42, 51, 32, 23, 30, 45, 64, 95]], dtype=int32)

In [129]:
arr2[0:10:3]

array([[36, 67, 86, 83, 99, 54, 25, 99, 34, 65],
       [ 4, 44,  6,  6, 59, 83, 40, 51, 42,  2],
       [14, 68, 97, 36, 15, 54, 67, 96, 52, 81],
       [37, 61, 42, 51, 32, 23, 30, 45, 64, 95]], dtype=int32)

In [130]:
arr2

array([[36, 67, 86, 83, 99, 54, 25, 99, 34, 65],
       [99, 38, 96, 76, 69, 84, 37, 61,  7, 19],
       [64, 17, 33, 90, 75, 87, 83, 70, 41, 79],
       [ 4, 44,  6,  6, 59, 83, 40, 51, 42,  2],
       [96, 12, 78, 37,  6,  0, 90, 91, 52, 71],
       [34, 46, 34, 99, 68, 62, 58, 66, 95, 12],
       [14, 68, 97, 36, 15, 54, 67, 96, 52, 81],
       [68, 47, 82, 53, 83, 52, 20, 51, 38, 72],
       [60, 90, 47, 72, 42, 73,  2, 65, 43, 47],
       [37, 61, 42, 51, 32, 23, 30, 45, 64, 95]], dtype=int32)

In [131]:
arr2[3:]

array([[ 4, 44,  6,  6, 59, 83, 40, 51, 42,  2],
       [96, 12, 78, 37,  6,  0, 90, 91, 52, 71],
       [34, 46, 34, 99, 68, 62, 58, 66, 95, 12],
       [14, 68, 97, 36, 15, 54, 67, 96, 52, 81],
       [68, 47, 82, 53, 83, 52, 20, 51, 38, 72],
       [60, 90, 47, 72, 42, 73,  2, 65, 43, 47],
       [37, 61, 42, 51, 32, 23, 30, 45, 64, 95]], dtype=int32)

In [132]:
arr

array([0, 1, 2, 3, 4, 5])

In [133]:
arr.max() 

np.int64(5)

In [134]:
arr.min()

np.int64(0)

In [135]:
arr

array([0, 1, 2, 3, 4, 5])

In [136]:
arr.mean()

np.float64(2.5)

In [137]:
arr

array([0, 1, 2, 3, 4, 5])

In [138]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [139]:
from numpy import * # 256 function called internally
a = array([1,2,3,4,9])
median(a)

np.float64(3.0)

# Without work on import* can you please find the median, mode)

In [140]:
arr

array([0, 1, 2, 3, 4, 5])

In [141]:
arr.reshape(3,2)  

array([[0, 1],
       [2, 3],
       [4, 5]])

In [142]:
arr.reshape(6,1)  

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [143]:
arr.reshape(1,6) 

array([[0, 1, 2, 3, 4, 5]])

In [144]:
arr

array([0, 1, 2, 3, 4, 5])

In [145]:
arr.reshape(2,4) 

ValueError: cannot reshape array of size 6 into shape (2,4)

In [ ]:
arr

In [ ]:
arr.reshape(3,2,order='C') 

In [ ]:
arr.reshape(2,3,order='C') 

In [ ]:
arr.reshape(2,3,order='F') # print element with fortran 

In [ ]:
arr.reshape(2,3,order='A') # A almost give you c type output 

In [ ]:
# importing Numpy package 
import numpy as np

# creating a Numpy array
num_array = np.arange(100).reshape(20, 5)
print(num_array)

# Display array in Fortran order 

print("\n  C type array:")
for num_array in np.nditer(num_array, order="C"):
	print(num_array,end=' ')

In [146]:
# importing Numpy package 
import numpy as np

# creating a Numpy array
num_array = np.arange(100).reshape(20, 5)
print(num_array)

# Display array in Fortran order 

print("\n  C type array:")
for num_array in np.nditer(num_array, order="F"):
	print(num_array,end=' ')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]

  C type array:
0 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 1 6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96 2 7 12 17 22 27 32 37 42 47 52 57 62 67 72 77 82 87 92 97 3 8 13 18 23 28 33 38 43 48 53 58 63 68 73 78 83 88 93 98 4 9 14 19 24 29 34 39 44 49 54 59 64 69 74 79 84 89 94 99 

In [147]:
arr.

SyntaxError: invalid syntax (1696555592.py, line 1)

In [148]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [149]:
arr.reshape(1,4)  

ValueError: cannot reshape array of size 6 into shape (1,4)

In [150]:
arr.reshape(1,6)  

array([[0, 1, 2, 3, 4, 5]])

In [151]:
arr.reshape(6,1)  

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [152]:
arr.reshape(2,6) 

ValueError: cannot reshape array of size 6 into shape (2,6)

In [153]:
arr.reshape(3,3) 

ValueError: cannot reshape array of size 6 into shape (3,3)

In [154]:
arr

array([0, 1, 2, 3, 4, 5])

In [155]:
arr.reshape(3,2)  

array([[0, 1],
       [2, 3],
       [4, 5]])

## Indexing

In [156]:
mat = np.arange(0,100).reshape(10,10) 

In [157]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [158]:
row = 4
col = 5

In [159]:
col

5

In [160]:
row

4

In [161]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [162]:
mat[row,col] 

np.int64(45)

In [163]:
mat[4,5] 

np.int64(45)

In [164]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [165]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [166]:
col = 6

In [167]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [168]:
mat[7] # befault it represent to rows

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [169]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [170]:
# With Slices
mat[:,col] 

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [171]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [172]:
mat[:, -1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [173]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [174]:
mat[row,:] 

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [175]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [176]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [177]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [178]:
mat[:col] 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [179]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [180]:
row

4

In [181]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [182]:
mat[:row]  

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [183]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [184]:
mat[row:] 

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [185]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [186]:
mat[:,8] 

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [187]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [188]:
mat[:,-1] 

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [189]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [190]:
row

4

In [191]:
col

6

In [192]:
mat[:,col] 

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [193]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [194]:
mat[1,4]

np.int64(14)

In [195]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [196]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [197]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [198]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [199]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [200]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [201]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [202]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [203]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [204]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [205]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [206]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [207]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [208]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [209]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [210]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [211]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [212]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [213]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [214]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [215]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [216]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [217]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [218]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [219]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [220]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [221]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [222]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [223]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [224]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [225]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [226]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [227]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [228]:
mat[2:6,2:4] # 1:5 --> only row part /// 1:3 -- it indicates only column parts

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [229]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [230]:
mat[0,1]

np.int64(1)

In [231]:
mat[1,6]

np.int64(16)

In [232]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [233]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [234]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [235]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [236]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [237]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [238]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [239]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [240]:
mat[3,5]

np.int64(35)

In [241]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [242]:
mat[1:2,2:4] 

array([[12, 13]])

In [243]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [244]:
mat[2:3,2:3] 

array([[22]])

In [245]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [246]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [247]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [248]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [249]:
mat[2:3,4:5]

array([[24]])

## Masking

In [250]:
mat # we also called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [251]:
id(mat)

2818448468624

In [252]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [253]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [254]:
mat[mat==50] 

array([50])

In [255]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [256]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [257]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [258]:
a1 = mat[mat<50] 
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [259]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [260]:
a2 = mat[mat>50] 
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [261]:
a3 = mat[mat<=50] 
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [262]:
a4 = mat[mat==50]
a4

array([50])

# python program to generat otp 

In [263]:
import random

def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

# Example usage
otp_length = 4  # You can change this to any length you prefer
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

Your OTP is: 0312
