# Array in Python

In [1]:
from array import * 
arr = array('i',[])

n = int(input('Enter the length of the array'))

for i in range(5):
    x = int(input('Enter the next value'))
    arr.append(x)
print(arr)

Enter the length of the array 4
Enter the next value 3
Enter the next value 2
Enter the next value 1
Enter the next value 5
Enter the next value 6


array('i', [3, 2, 1, 5, 6])


In [2]:
# Way of creating array using numpy

In [3]:
from numpy import *
arr = array([1,2,3,4,5])
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [4]:
print(arr.dtype)

int64


In [5]:
arr = array([1,2,3,4,5.9])
print(arr)

[1.  2.  3.  4.  5.9]


In [6]:
print(arr.dtype)

float64


In [7]:
arr2 = array([1,2,3,4,5.9],float)
arr2

array([1. , 2. , 3. , 4. , 5.9])

In [8]:
arr3 = array([1,2,3,4,5.6],int)
arr3

array([1, 2, 3, 4, 5])

In [9]:
import numpy as np

In [10]:
arr4 = np.linspace(0, 16, 10) # break the code between 10 spaces between 0 to 16 but why decimal becuase we break into parts thats why it is floats
arr4

array([ 0.        ,  1.77777778,  3.55555556,  5.33333333,  7.11111111,
        8.88888889, 10.66666667, 12.44444444, 14.22222222, 16.        ])

In [11]:
arr5 = np.arange(0,10,2) # arange - as range
arr5

array([0, 2, 4, 6, 8])

In [12]:
arr6 = np.zeros(5)
arr6

array([0., 0., 0., 0., 0.])

In [13]:
arr7 = np.ones(5)
arr7

array([1., 1., 1., 1., 1.])

In [14]:
import numpy as np

In [15]:
np.__version__

'2.1.3'

In [16]:
import sys 
sys.version

'3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, 16:37:03) [MSC v.1929 64 bit (AMD64)]'

## create a list 

In [17]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [18]:
type(my_list)

list

### How to convert list to array

In [19]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [20]:
type(arr)

numpy.ndarray

In [21]:
print(type(my_list))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [22]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [23]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [24]:
np.arange(5,100,10)

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [25]:
np.arange(20,10)   # ist arr should less

array([], dtype=int64)

In [26]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

## Parameter tunning 

* what system gives/generates automatically

In [27]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

## Hyperparameter Tunning
* If user changes the system parameter

In [28]:
np.zeros(5,dtype=int)       # float ---->int


array([0, 0, 0, 0, 0])

In [29]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [30]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [31]:
np.zeros((10,3),dtype=int)    #(row,column)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [32]:
np.ones(4)

array([1., 1., 1., 1.])

In [33]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [34]:
np.two(4)

AttributeError: module 'numpy' has no attribute 'two'

In [26]:
rand(2,3)

NameError: name 'rand' is not defined

In [27]:
random.rand(2,3)

NameError: name 'random' is not defined

In [31]:
np.random.rand(2)     #it wil geneate flaot value

array([0.8559065 , 0.44552645])

In [30]:
np.random.rand(2,3)

array([[0.07575919, 0.9847803 , 0.84019159],
       [0.74953766, 0.35747677, 0.38662851]])

In [33]:
np.random.randint(2)    #it will generste only random integer between 0 and n-1

1

In [35]:
np.random.randint(2,9)

4

In [37]:
np.random.randint(2,9,4)     #genearte random integer between 2 - 9 where 9 is exclude

array([8, 8, 7, 4], dtype=int32)

In [ ]:
def generate_otp(length=4):
    otp: ''.join([str(np.random.randint

In [38]:
np.random.randint(10,40,(10,10))      

array([[13, 36, 27, 12, 15, 13, 34, 39, 30, 32],
       [30, 25, 32, 18, 27, 10, 33, 37, 17, 25],
       [29, 28, 26, 32, 19, 39, 13, 18, 11, 28],
       [32, 33, 29, 28, 24, 15, 21, 23, 19, 26],
       [35, 33, 22, 10, 29, 18, 36, 18, 34, 30],
       [37, 17, 19, 34, 24, 38, 14, 36, 37, 30],
       [33, 15, 15, 16, 12, 20, 28, 26, 36, 27],
       [37, 20, 11, 14, 13, 15, 20, 22, 19, 22],
       [33, 21, 21, 24, 12, 33, 23, 23, 28, 12],
       [27, 30, 26, 20, 25, 13, 28, 21, 15, 23]], dtype=int32)

In [39]:
arr1=np.random.randint(10,40,(10,10))      
print(arr1)

[[19 35 29 34 33 15 31 31 27 30]
 [12 10 22 28 25 11 12 22 33 39]
 [11 23 23 21 20 27 34 36 13 18]
 [21 11 17 20 18 10 21 31 30 38]
 [32 34 39 19 32 22 24 31 16 16]
 [39 13 17 37 22 18 38 21 14 32]
 [26 36 15 31 31 28 34 22 21 34]
 [21 17 17 19 23 25 30 20 10 19]
 [38 34 36 34 13 28 11 36 15 28]
 [38 15 13 39 37 13 12 24 22 19]]
